---
version: "3.8"
services:
  movies:
    image: ashok109s/paytmmoviess:latest
    ports:
      - 95:80
    deploy:
      replicas: 3
  train:
    image: ashok109s/paytmtrains:latest
    ports:
      - 96:80
    deploy:
      replicas: 3
  recharge:
    image: ashok109s/paytmrecharges:latest
    ports:
      - 97:80
    deploy:
      replicas: 3
  dth:
    image: ashok109s/paytmdths:latest
    ports:
      - 98:80
    deploy:
      replicas: 3
