---
version: "3.8"
services:
  movies:
    image: ashok109s/paytmmoviess1:v1
    ports:
      - 93:80
    deploy:
      replicas: 3
  train:
    image: ashok109s/paytmtrainss
    ports:
      - 91:80
    deploy:
      replicas: 3
  recharge:
    image: ashok109s/paytmrecharges1:v1
    ports:
      - 92:80
    deploy:
      replicas: 3
  dth:
    image: ashok109s/paytmdths1:v1
    ports:
      - 94:80
    deploy:
      replicas: 3
